export const PRODUCT_LIST_REQUEST="PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS="PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL="PRODUCT_LIST_FAIL"


export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL="PRODUCT_DETAILS_FAIL"


export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"


export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL"


export const USER_REGISTER_REQUEST="USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL="USER_REGISTER_FAIL"


export const PRODUCT_UPLOAD_REQUEST="PRODUCT_UPLOAD_REQUEST"
export const PRODUCT_UPLOAD_SUCCESS="PRODUCT_UPLOAD_SUCCESS"
export const PRODUCT_UPLOAD_FAIL="PRODUCT_UPLOAD_FAIL"


export const PRODUCT_DELETE_REQUEST="PRODUCT_DELETE_REQUEST"
export const PRODUCT_DELETE_SUCCESS="PRODUCT_DELETE_SUCCESS"
export const PRODUCT_DELETE_FAIL="PRODUCT_DELETE_FAIL"


